config-version = "2.7"
bind = "0.0.0.0:25565"
motd = ${MTOD}
show-max-players = ${MAXPLAYER}
online-mode = false
force-key-authentication = false
prevent-client-proxy-connections = false
player-info-forwarding-mode = "LEGACY"
forwarding-secret-file = "forwarding.secret"
announce-forge = false
kick-existing-players = false
enable-player-address-logging = true

[servers]
lobby = "localhost:65535"
0 = ${SERVER0}
1 = ${SERVER1}
2 = ${SERVER2}
3 = ${SERVER3}
4 = ${SERVER4}
5 = ${SERVER5}
6 = ${SERVER6}
7 = ${SERVER7}
8 = ${SERVER8}
9 = ${SERVER9}
try = [ "lobby",]

[forced-hosts]
"example.com" = [ "examplecom",]

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3000
connection-timeout = 5000
read-timeout = 30000
haproxy-protocol = false
tcp-fast-open = false
bungee-plugin-message-channel = true
show-ping-requests = false
failover-on-unexpected-server-disconnect = true
announce-proxy-commands = true
log-command-executions = false
log-player-connections = true

[query]
enabled = false
port = 25577
map = "Velocity"
show-plugins = false
